name: vroom
description: Biker Social - cross-platform Flutter app for bikers in Nepal
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.0.0
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  flutter_chat_ui: ^1.4.0
  onesignal_flutter: ^3.0.0
  provider: ^6.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  image_picker: ^0.8.5
  intl: ^0.18.1
  video_player: ^2.4.5
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
